name: erpnext_social_media_marketing_docker

x-customizable-image: &customizable_image
  image: ghcr.io/b-robotized/erpnext_social_media_marketing:stable
  build:
    context: ..
    dockerfile: docker/Dockerfile
  pull_policy: never
  restart: unless-stopped

x-backend-defaults: &backend_defaults
  <<: *customizable_image

services:
  backend:
    <<: *backend_defaults
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    networks:
      default: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  configurator:
    <<: *customizable_image
    restart: "no"
    command:
      - |
        ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
       
        echo "Checking Database Connection..."
        until mysqladmin ping -h db --silent --password=123; do
          echo "→ Database not reachable. Waiting..."
          sleep 2
        done
        echo "✓ Database is reachable."
      
        if [ ! -d "sites/${SITE_NAME}" ]; then
          bench new-site ${SITE_NAME} \
            --db-host            ${DB_HOST} \
            --db-port            ${DB_PORT} \
            --db-name            ${DB_NAME} \
            --db-password        ${DB_PASSWORD} \
            --db-root-password   ${DB_ROOT_PASSWORD} \
            --admin-password     ${ADMIN_PASSWORD} \
            --install-app        erpnext \
            --install-app        erpnext_social_media_marketing
        else
          echo "Site ${SITE_NAME} already exists. Skipping creation."
        fi

        echo "➤ Site created – extend DB access rights"

        mysql -h "$DB_HOST" -u root -p"$DB_ROOT_PASSWORD" -e "\
          CREATE USER IF NOT EXISTS '$DB_NAME'@'%' IDENTIFIED BY '$DB_PASSWORD'; \
          GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_NAME'@'%'; \
          FLUSH PRIVILEGES;"
        echo "✓ Extended permissions. Setup completed."
    depends_on:
      db:
        condition: service_healthy
        required: true
      redis-cache:
        condition: service_started
        required: true
      redis-queue:
        condition: service_started
        required: true
    entrypoint:
      - bash
      - -c
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    networks:
      default: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  db:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: "123"
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost --password=123
      interval: 1s
      retries: 20
    image: mariadb:10.6
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
        volume: {}

  frontend:
    <<: *customizable_image
    command:
      - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
        required: true
      websocket:
        condition: service_started
        required: true
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  queue-long:
    <<: *customizable_image
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    networks:
      default: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  queue-short:
    <<: *customizable_image
    command:
      - bench
      - worker
      - --queue
      - short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    networks:
      default: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  redis-cache:
    image: redis:6.2-alpine
    networks:
      default: null
    restart: unless-stopped

  redis-queue:
    image: redis:6.2-alpine
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}

  scheduler:
    <<: *customizable_image
    command:
      - bench
      - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    networks:
      default: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

  websocket:
    <<: *customizable_image
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
        required: true
    networks:
      default: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}

networks:
  default:
    name: erpnext_social_media_marketing_docker_default

volumes:
  db-data:
    name: erpnext_social_media_marketing_docker_db-data
  redis-queue-data:
    name: erpnext_social_media_marketing_docker_redis-queue-data
  sites:
    name: erpnext_social_media_marketing_docker_sites
